### ISSUE TITLE
登录界面闪退

### ISSUE THREAD

**Issue by Starduster-lin** [wojiangkuanglong/bilibili-lucky#1]
不明白图鉴账号是什么 所以我只填了b站账号密码 

执行npm start调取浏览器后，登录验证（非滑块，点击顺序中文）页面，发生闪退
npm报错如下：

file:///G:/%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/bilibili-lucky-main/bilibili-lucky-main/index.js:62
    coordinate: data.data.result.split("|").map(
                                 ^

TypeError: Cannot read properties of undefined (reading 'split')
    at getCoordinate (file:///G:/%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/bilibili-lucky-main/bilibili-lucky-main/index.js:62:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///G:/%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/bilibili-lucky-main/bilibili-lucky-main/index.js:107:25
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilibili-lucky@1.0.0 start: `node -r dotenv/config index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilibili-lucky@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\12911\AppData\Roaming\npm-cache\_logs\2023-04-08T08_47_33_258Z-debug.log

**Comment by Starduster-lin** [comment]
终于搞明白图鉴账号是什么了
{
  success: false,
  code: '-1',
  message: 'NoBalanceException: 余额不足',
  data: ''
}
注册充值后终于可以了 谢谢dalao！改天试下部署在青龙上面

**Comment by wojiangkuanglong** [comment]
> 终于搞明白图鉴账号是什么了 { success: false, code: '-1', message: 'NoBalanceException: 余额不足', data: '' } 注册充值后终于可以了 谢谢dalao！改天试下部署在青龙上面

**Comment by wojiangkuanglong** [comment]
> 终于搞明白图鉴账号是什么了 { success: false, code: '-1', message: 'NoBalanceException: 余额不足', data: '' } 注册充值后终于可以了 谢谢dalao！改天试下部署在青龙上面

感谢使用，有问题持续反馈
