### ISSUE TITLE
默认的抽奖专栏 元素选择出错

### ISSUE THREAD

**Issue by Starduster-lin** [wojiangkuanglong/bilibili-lucky#2]
4.11起大锦鲤的每日的专栏中，原来的抽奖链接改为短链接了，抽奖链接的css发生了改变，导致抓取不了链接，需要简单改下抓取链接按钮的代码。
![image](https://user-images.githubusercontent.com/64762565/231211925-63cba31b-92a2-4484-a68e-b1304271b9b1.png)

**Comment by wojiangkuanglong** [comment]
> 4.11起大锦鲤的每日的专栏中，原来的抽奖链接改为短链接了，抽奖链接的css发生了改变，导致抓取不了链接，需要简单改下抓取链接按钮的代码。 ![image](https://user-images.githubusercontent.com/64762565/231211925-63cba31b-92a2-4484-a68e-b1304271b9b1.png)

已修复
